import Head from 'next/head';
import Header from '../components/Header';
import Results from '../components/Results';
import { API_KEY } from '../utils/requests';

export default function Movie({ results }) {
	return (
		<div>
			<Head>
				<title>Hulu 2.0s</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Results results={results} />
		</div>
	);
}

export async function getServerSideProps(context) {
	const movie = context.query.movie;

	const request = await fetch(
		`https://api.themoviedb.org/3/movie/${movie}?api_key=${API_KEY}`
	)
		.then((res) => {
			console.log({ res });
			return res ? res.json() : { results: {} };
		})
		.catch((err) => {
			console.log({ err });
		});

	return {
		props: {
			results: [request],
		},
	};
}
